-- =========================================================
			-- Section 1: Business KPIs
-- =========================================================

-- ============================================================
-- Query 1: Total Sales
-- Business Question:
-- What is the total sales revenue generated by the business?
-- ============================================================
select round(sum(Sales),2) as Total_Sales
from orders;

-- ============================================================
-- Query 2: Total Profit
-- Business Question:
-- What is the total profit earned by the business?
-- ============================================================
select round(sum(profit),2) as Total_Profit
from orders;

-- ============================================================
-- Query 3: Total Quantity Sold
-- Business Question:
-- How many product units have been sold across all orders?
-- ============================================================
select sum(Quantity) as Total_Quantity
from orders;

-- ============================================================
-- Query 4: Total Orders
-- Business Question:
-- How many unique orders have been placed by customers?
-- ============================================================
select COUNT(DISTINCT `Order ID`) as Total_Orders
from orders;

-- ============================================================
-- Query 5: Total Customers
-- Business Question:
-- How many unique customers have made purchases?
-- ============================================================
select COUNT(DISTINCT `Customer ID`) as Total_Customers
from orders;

-- ============================================================
-- Query 6: Total Products
-- Business Question:
-- How many unique products have been sold?
-- ============================================================
select count(distinct `Product ID`) as Total_Products
from orders;

