/*
-- =========================================================
Project Name : Retail Sales Analytics
Dataset      : Sample Superstore
Author       : Kaustubh Waghmare
Description  : SQL Exploratory Data Analysis (EDA)
-- =========================================================
*/

USE retail_sales_analysis;

-- =========================================================
			-- Section 1: Business KPIs
-- =========================================================

-- ============================================================
-- Query 1: Total Sales
-- Business Question:
-- What is the total sales revenue generated by the business?
-- ============================================================
select round(sum(Sales),2) as Total_Sales
from orders;

-- ============================================================
-- Query 2: Total Profit
-- Business Question:
-- What is the total profit earned by the business?
-- ============================================================
select round(sum(profit),2) as Total_Profit
from orders;

-- ============================================================
-- Query 3: Total Quantity Sold
-- Business Question:
-- How many product units have been sold across all orders?
-- ============================================================
select sum(Quantity) as Total_Quantity
from orders;

-- ============================================================
-- Query 4: Total Orders
-- Business Question:
-- How many unique orders have been placed by customers?
-- ============================================================
select COUNT(DISTINCT `Order ID`) as Total_Orders
from orders;

-- ============================================================
-- Query 5: Total Customers
-- Business Question:
-- How many unique customers have made purchases?
-- ============================================================
select COUNT(DISTINCT `Customer ID`) as Total_Customers
from orders;

-- ============================================================
-- Query 6: Total Products
-- Business Question:
-- How many unique products have been sold?
-- ============================================================
select count(distinct `Product ID`) as Total_Products
from orders;



-- ============================================================
				--section2: Customer Analysis
-- ============================================================

-- ============================================================
-- Query 7: Sales, Profit & Quantity by Segment
-- Business Question:
-- Which customer segment contributes the highest sales, profit, and quantity sold?
-- ============================================================
select
    `Segment`,
    ROUND(SUM(Sales),2) AS Total_Sales,
    ROUND(SUM(Profit),2) AS Total_Profit,
    SUM(Quantity) AS Total_Quantity
from orders
group by `Segment`
order by Total_Sales DESC;


-- ============================================================
-- Query 8: Customer Count by Segment
-- Business Question:
-- Which customer segment has the highest number of unique customers?
-- ============================================================
select 
	`Segment`,
    COUNT(DISTINCT `Customer ID`) as Total_Customers
    
FROM orders
group by `Segment`
order by Total_Customers desc;

-- ============================================================
-- Query 9: Average Order Value by Segment
-- Business Question:
-- Which customer segment has the highest average order value?
-- ============================================================
select 
    `Segment`,
    round(AVG(Sales),2) as Avg_Order_Value
FROM orders
group by `Segment`
order by Avg_Order_Value desc;


-- ============================================================
-- Query 10: Top 10 Customers by Sales
-- Business Question:
-- Which customers generate the highest sales revenue?
-- ============================================================
select 
	`Customer Name`,
    ROUND(SUM(Sales),2) as Total_Sales
    
FROM orders
group by `Customer Name`
order By Total_Sales desc
limit 10;


-- ============================================================
-- Query 11: Top 10 Customers by Profit
-- Business Question:
-- Which customers generate the highest profit?
-- ============================================================
select 
    `Customer Name`,
    ROUND(SUM(Profit), 2) as Total_Profit
FROM orders
group by `Customer Name`
order by Total_Profit desc
limit 10;

-- ============================================================
-- Query 12: Customers with Highest Number of Orders
-- Business Question:
-- Which customers place the highest number of orders?
-- ============================================================
select 
	`Customer Name`,
    count(distinct `Order ID`) as Total_Orders
    
FROM orders
group by `Customer Name`
order by Total_Orders DESC
limit 10;

-- ============================================================
-- Query 13: Top 10 Customers by Quantity Purchased
-- Business Question:
-- Which customers purchase the highest quantity of products?
-- ============================================================
select 
	`Customer Name`,
	sum(Quantity) as Total_Quantity
FROM orders
group by `Customer Name`
order by Total_Quantity DESC
limit 10;



-- =============================================================
				-- section 3: Geographic  Analysis
-- =============================================================

-- ================================================================
-- Query 14:  country-wise Sales & Profit
-- Business Question:
--Which Country generates the highest sales and profit?
-- ================================================================	
select 
    `Country`,
    ROUND(sum(Sales),2) as Total_Sales,
    ROUND(sum(Profit),2) as Total_Profit
FROM orders
group by `Country` 
order by Total_Sales desc;


================================================================
-- Query 15:  State-wise Sales
-- Business Question:
-- Which states generate the highest sales revenue?
================================================================	
select 
    `State`,
    ROUND(sum(sales),2) as Total_sales
FROM orders
group by `State`
order by Total_Sales desc;

-- =============================================================
-- Query 16: State-wise Profit
-- Business Question:
-- Which states generate the highest profit?
-- =============================================================
select 
    `state`,
    ROUND(sum(Profit),2) as Total_Profit
FROM orders
group by `State`
order by Total_Profit desc;

-- =============================================================
-- Query 17: Top 10 Cities by Sales
-- Business Question:
-- Which cities generate the highest sales revenue?
-- =============================================================
select 
    `City`,
    ROUND(sum(Sales),2) as Total_Sales

FROM orders
group by `City`
order by Total_Sales desc
limit 10;

-- ==============================================================
-- Query 18: Top 10 Cities by Profit
-- Business Question:
-- which cities generate the highest profit?
-- ==============================================================
select
	`City`,
	ROUND(SUM(Profit),2) as Total_Profit
FROM orders
group by `City`
order by Total_Profit desc
limit 10;

--===============================================================
	-- Quesry 19: Total Orders by State
	-- Business Question:
	-- Which states have the highest number of orders?
--================================================================
select 
	`State`,
	COUNT(DISTINCT `Order ID`) as Total_Orders
FROM orders
group by `State`
order by Total_Orders desc;





-- ============================================================
				-- section 4: Product  Analysis
-- =============================================================

--===============================================================
	-- Quesry 20: Category-wise Sales
	-- Business Question:
	-- Which product category generates the highest sales revenue?
--================================================================
select  
`Category`,
ROUND(sum(sales),2) as Total_Sales

from orders
group by `Category`
order by Total_Sales desc;

--===============================================================
	-- Quesry 21: Category-wise Profit
	-- Business Question:
	-- Which product category generates the highest profit?
--================================================================
select 	
	`Category`,
    round(sum(Profit),2) as Total_Profit
    
FROM orders
group by `Category`
order by Total_profit desc;

--===============================================================
	-- Quesry 22: Sub-Category-wise Sales
	-- Business Question:
	-- Which product sub-category genrates the highest sales revenue?
--================================================================
select  
	`Sub-Category`,
	ROUND(sum(Sales),2) as Total_Sales

from orders
group by `Sub-Category`
order by Total_Sales desc;

--===============================================================
	-- Quesry 23: Sub-Category-wise Profit
	-- Business Question:
	-- Which product sub-category genrates the highest Profit?
--================================================================
select 	
	`Sub-Category`,
    round(sum(Profit),2) as Total_Profit
    
FROM orders
group by `Sub-Category`
order by Total_profit desc;

--===============================================================
	-- Quesry 24: Top 10 Products by Sales
	-- Business Question:
	-- Which product generate the highest sales revenue?
--================================================================
select
`Product Name`,
round(sum(Sales),2) as Total_Sales

FROM orders
group by `Product Name`
order by Total_Sales desc
limit 10;


--===============================================================
	-- Quesry 25: Top 10 Products by Profit
	-- Business Question:
	-- Which product generate the highest profit?
--================================================================
select
`Product Name`,
round(sum(Profit),2) as Total_Profit

FROM orders
group by `Product Name`
order by Total_Profit desc
limit 10;

--===============================================================
	-- Quesry 26: Top 10 Loss-Making Products
	-- Business Question:
	-- Which product generate the highest losses?
--================================================================
select 
	`Product Name`,
    round(sum(Profit),2) as Total_Loss
from orders
group by `Product Name`
Having sum(Profit)<0
order by Total_Loss ASC
limit 10;

--===============================================================
	-- Quesry 27: Category-wise Quantity Sold
	-- Business Question:
	-- Which product category has the highest quantity sold?
--================================================================
select 
	`Category`,
    sum(Quantity) as Total_Quantity
    
from orders
group by `Category`
order by Total_Quantity desc

--===============================================================
	-- Quesry 28: Sub-Category-wise Quantity Sold
	-- Business Question:
	-- Which product sub-category has the highest quantity sold?
--===============================================================
select 
	`Sub-Category`,
    sum(Quantity) as Total_Quantity
    
from orders
group by `Sub-Category`
order by Total_Quantity desc

--=================================================================
	-- Quesry 29: Average Disocunt by category
	-- Business Question:
	-- Which product category receives the highest average discount?
--==================================================================
select 
	`Category`,
    round(avg(Discount),2) as Average_Discount
    
from orders
group by Category
order by Average_Discount desc

--=====================================================================
	-- Query 30: Average Discount by Sub-Category
	-- Business Question:
	-- Which product sub-category receives the highest average discount?
--======================================================================
select 
	`Sub-Category`,
    round(avg(Discount),2) as Average_Discount
    
from orders
group by `Sub-Category`
order by Average_Discount desc
