/*
-- =========================================================
Project Name : Retail Sales Analytics
Dataset      : Sample Superstore
Author       : Kaustubh Waghmare
Description  : SQL Exploratory Data Analysis (EDA)
-- =========================================================
*/

USE retail_sales_analysis;

-- =========================================================
			-- Section 1: Business KPIs
-- =========================================================

-- ============================================================
-- Query 1: Total Sales
-- Business Question:
-- What is the total sales revenue generated by the business?
-- ============================================================
select round(sum(Sales),2) as Total_Sales
from orders;

-- ============================================================
-- Query 2: Total Profit
-- Business Question:
-- What is the total profit earned by the business?
-- ============================================================
select round(sum(profit),2) as Total_Profit
from orders;

-- ============================================================
-- Query 3: Total Quantity Sold
-- Business Question:
-- How many product units have been sold across all orders?
-- ============================================================
select sum(Quantity) as Total_Quantity
from orders;

-- ============================================================
-- Query 4: Total Orders
-- Business Question:
-- How many unique orders have been placed by customers?
-- ============================================================
select COUNT(DISTINCT `Order ID`) as Total_Orders
from orders;

-- ============================================================
-- Query 5: Total Customers
-- Business Question:
-- How many unique customers have made purchases?
-- ============================================================
select COUNT(DISTINCT `Customer ID`) as Total_Customers
from orders;

-- ============================================================
-- Query 6: Total Products
-- Business Question:
-- How many unique products have been sold?
-- ============================================================
select count(distinct `Product ID`) as Total_Products
from orders;



-- ============================================================
				--section2: Customer Analysis
-- ============================================================

-- ============================================================
-- Query 7: Sales, Profit & Quantity by Segment
-- Business Question:
-- Which customer segment contributes the highest sales, profit, and quantity sold?
-- ============================================================
select
    `Segment`,
    ROUND(SUM(Sales),2) AS Total_Sales,
    ROUND(SUM(Profit),2) AS Total_Profit,
    SUM(Quantity) AS Total_Quantity
from orders
group by `Segment`
order by Total_Sales DESC;


-- ============================================================
-- Query 8: Customer Count by Segment
-- Business Question:
-- Which customer segment has the highest number of unique customers?
-- ============================================================
select 
	`Segment`,
    COUNT(DISTINCT `Customer ID`) as Total_Customers
    
FROM orders
group by `Segment`
order by Total_Customers desc;

-- ============================================================
-- Query 9: Average Order Value by Segment
-- Business Question:
-- Which customer segment has the highest average order value?
-- ============================================================
select 
    `Segment`,
    round(AVG(Sales),2) as Avg_Order_Value
FROM orders
group by `Segment`
order by Avg_Order_Value desc;


-- ============================================================
-- Query 10: Top 10 Customers by Sales
-- Business Question:
-- Which customers generate the highest sales revenue?
-- ============================================================
select 
	`Customer Name`,
    ROUND(SUM(Sales),2) as Total_Sales
    
FROM orders
group by `Customer Name`
order By Total_Sales desc
limit 10;


-- ============================================================
-- Query 11: Top 10 Customers by Profit
-- Business Question:
-- Which customers generate the highest profit?
-- ============================================================
select 
    `Customer Name`,
    ROUND(SUM(Profit), 2) as Total_Profit
FROM orders
group by `Customer Name`
order by Total_Profit desc
limit 10;

-- ============================================================
-- Query 12: Customers with Highest Number of Orders
-- Business Question:
-- Which customers place the highest number of orders?
-- ============================================================
select 
	`Customer Name`,
    count(distinct `Order ID`) as Total_Orders
    
FROM orders
group by `Customer Name`
order by Total_Orders DESC
limit 10;

-- ============================================================
-- Query 13: Top 10 Customers by Quantity Purchased
-- Business Question:
-- Which customers purchase the highest quantity of products?
-- ============================================================
select 
	`Customer Name`,
	sum(Quantity) as Total_Quantity
FROM orders
group by `Customer Name`
order by Total_Quantity DESC
limit 10;



-- =============================================================
				-- section 3: Geographic  Analysis
-- =============================================================

-- ================================================================
-- Query 14:  country-wise Sales & Profit
-- Business Question:
--Which Country generates the highest sales and profit?
-- ================================================================	
select 
    `Country`,
    ROUND(sum(Sales),2) as Total_Sales,
    ROUND(sum(Profit),2) as Total_Profit
FROM orders
group by `Country` 
order by Total_Sales desc;


-- ================================================================
-- Query 15:  State-wise Sales
-- Business Question:
-- Which states generate the highest sales revenue?
-- ================================================================	
select 
    `State`,
    ROUND(sum(sales),2) as Total_sales
FROM orders
group by `State`
order by Total_Sales desc;

-- =============================================================
-- Query 16: State-wise Profit
-- Business Question:
-- Which states generate the highest profit?
-- =============================================================
select 
    `state`,
    ROUND(sum(Profit),2) as Total_Profit
FROM orders
group by `State`
order by Total_Profit desc;

-- =============================================================
-- Query 17: Top 10 Cities by Sales
-- Business Question:
-- Which cities generate the highest sales revenue?
-- =============================================================
select 
    `City`,
    ROUND(sum(Sales),2) as Total_Sales

FROM orders
group by `City`
order by Total_Sales desc
limit 10;

-- ==============================================================
-- Query 18: Top 10 Cities by Profit
-- Business Question:
-- which cities generate the highest profit?
-- ==============================================================
select
	`City`,
	ROUND(SUM(Profit),2) as Total_Profit
FROM orders
group by `City`
order by Total_Profit desc
limit 10;

--===============================================================
	-- Quesry 19: Total Orders by State
	-- Business Question:
	-- Which states have the highest number of orders?
--================================================================
select 
	`State`,
	COUNT(DISTINCT `Order ID`) as Total_Orders
FROM orders
group by `State`
order by Total_Orders desc;





-- ============================================================
				-- section 4: Product  Analysis
-- =============================================================

--===============================================================
	-- Quesry 20: Category-wise Sales
	-- Business Question:
	-- Which product category generates the highest sales revenue?
--================================================================
select  
`Category`,
ROUND(sum(sales),2) as Total_Sales

from orders
group by `Category`
order by Total_Sales desc;

-- ===============================================================
	-- Quesry 21: Category-wise Profit
	-- Business Question:
	-- Which product category generates the highest profit?
-- ================================================================
select 	
	`Category`,
    round(sum(Profit),2) as Total_Profit
    
FROM orders
group by `Category`
order by Total_profit desc;

-- ===============================================================
	-- Quesry 22: Sub-Category-wise Sales
	-- Business Question:
	-- Which product sub-category genrates the highest sales revenue?
-- ================================================================
select  
	`Sub-Category`,
	ROUND(sum(Sales),2) as Total_Sales

from orders
group by `Sub-Category`
order by Total_Sales desc;

-- ===============================================================
	-- Quesry 23: Sub-Category-wise Profit
	-- Business Question:
	-- Which product sub-category genrates the highest Profit?
-- ================================================================
select 	
	`Sub-Category`,
    round(sum(Profit),2) as Total_Profit
    
FROM orders
group by `Sub-Category`
order by Total_profit desc;

-- ===============================================================
	-- Quesry 24: Top 10 Products by Sales
	-- Business Question:
	-- Which product generate the highest sales revenue?
-- ================================================================
select
`Product Name`,
round(sum(Sales),2) as Total_Sales

FROM orders
group by `Product Name`
order by Total_Sales desc
limit 10;


-- ===============================================================
	-- Quesry 25: Top 10 Products by Profit
	-- Business Question:
	-- Which product generate the highest profit?
-- ================================================================
select
`Product Name`,
round(sum(Profit),2) as Total_Profit

FROM orders
group by `Product Name`
order by Total_Profit desc
limit 10;

-- ===============================================================
	-- Quesry 26: Top 10 Loss-Making Products
	-- Business Question:
	-- Which product generate the highest losses?
-- ================================================================
select 
	`Product Name`,
    round(sum(Profit),2) as Total_Loss
from orders
group by `Product Name`
Having sum(Profit)<0
order by Total_Loss ASC
limit 10;

-- ===============================================================
	-- Quesry 27: Category-wise Quantity Sold
	-- Business Question:
	-- Which product category has the highest quantity sold?
-- ================================================================
select 
	`Category`,
    sum(Quantity) as Total_Quantity
    
from orders
group by `Category`
order by Total_Quantity desc

-- ===============================================================
	-- Quesry 28: Sub-Category-wise Quantity Sold
	-- Business Question:
	-- Which product sub-category has the highest quantity sold?
-- ===============================================================
select 
	`Sub-Category`,
    sum(Quantity) as Total_Quantity
    
from orders
group by `Sub-Category`
order by Total_Quantity desc

-- =================================================================
	-- Quesry 29: Average Disocunt by category
	-- Business Question:
	-- Which product category receives the highest average discount?
-- ==================================================================
select 
	`Category`,
    round(avg(Discount),2) as Average_Discount
    
from orders
group by Category
order by Average_Discount desc

-- =====================================================================
	-- Query 30: Average Discount by Sub-Category
	-- Business Question:
	-- Which product sub-category receives the highest average discount?
-- ======================================================================
select 
	`Sub-Category`,
    round(avg(Discount),2) as Average_Discount
    
from orders
group by `Sub-Category`
order by Average_Discount desc




-- ============================================================
		-- SECTION 5: SHIPPING ANALYSIS
-- ============================================================

-- ============================================================
-- Query 31: Ship Mode-wise Sales
-- Business Question:
-- Which shipping mode generates the highest sales revenue?
-- ============================================================
select 
	`Ship Mode`,
    round(sum(Sales),2) as 'Total_Sales'

from orders

group by `Ship Mode`
order by Total_Sales desc;


-- ============================================================
-- Query 32: Ship Mode-wise Profit
-- Business Question:
-- Which shipping mode generates the highest profit?
-- ============================================================
select 
	`Ship Mode`,
    round(sum(Profit),2) as 'Total_Profit'

from orders

group by `Ship Mode`
order by Total_Profit desc;

-- ============================================================
-- Query 33: Ship Mode-wise Orders
-- Business Question:
-- Which shipping mode is used for the highest number of customer orders?
-- ============================================================
select 
	`Ship Mode`,
    (count(Distinct `Order ID`)) as Total_Orders
from orders
group by `Ship Mode`
order by Total_Orders desc;


-- ============================================================
-- Query 34: Ship Mode-wise Quantity Sold
-- Business Question:
-- Which shipping mode delivers the highest quantity of products?
-- ============================================================
select 
	`Ship Mode`,
    sum(Quantity) as 'Total_Quantity'

from orders

group by `Ship Mode`
order by Total_Quantity desc;

-- ============================================================
-- Query 35: Average Shipping Time by Ship Mode
-- Business Question:
-- What is the average delivery time for each shipping mode?
-- ============================================================
select
`Ship Mode`,
round(
		avg(
			DATEDIFF(
					STR_TO_DATE(`Ship Date`, '%d-%m-%Y'),
					STR_TO_DATE(`Order Date`,'%d-%m-%Y')
                    )
			),
		2
	) as Average_shipping_time_days
from orders
group by `Ship Mode`
order by Average_shipping_time_days desc;

-- ============================================================
-- Query 36: Maximum Shipping Time by Ship Mode
-- Business Question:
-- Which shipping mode has the longest delivery time?
-- ============================================================
select
`Ship Mode`,
round(
		max(
			DATEDIFF(
					STR_TO_DATE(`Ship Date`, '%d-%m-%Y'),
					STR_TO_DATE(`Order Date`,'%d-%m-%Y')
                    )
			),
		2
	) as Average_shipping_time_days
from orders
group by `Ship Mode`
order by Average_shipping_time_days desc;

-- ============================================================
-- Query 37: Minimum Shipping Time by Ship Mode
-- Business Question:
-- Which shipping mode has the shortest delivery time?
-- ============================================================
select
`Ship Mode`,
round(
		min(
			DATEDIFF(
					STR_TO_DATE(`Ship Date`, '%d-%m-%Y'),
					STR_TO_DATE(`Order Date`,'%d-%m-%Y')
                    )
			),
		2
	) as Average_shipping_time_days
from orders
group by `Ship Mode`
order by Average_shipping_time_days desc;

-- ============================================================
-- Query 38: Average Sales per Order by Ship Mode
-- Business Question:
-- Which shipping mode has the highest average sales per order?
-- ============================================================
select 
	`Ship Mode`,
	round(AVG(Order_Sales),2) as Average_Sales_Per_Order
from 
(
	select 
		`Order ID`,
        `Ship Mode`,
        SUM(Sales) AS Order_Sales
	from orders
    GROUP BY `Order ID`,`Ship Mode`
) as OrderSummary

group by `Ship Mode`
order by Average_Sales_Per_Order desc ;


-- ============================================================
		-- SECTION 5: TIME ANALYSIS
-- ============================================================

-- ============================================================
-- Query 39: Year-wise Sales
-- Business Question:
-- How has sales revenue changed over the years?
-- ============================================================
select
	year(`Order Date`) as Order_Year,
    round(sum(Sales),2) as Total_Sales
from orders
group by Year(`Order Date`)
order by Order_Year;



-- ============================================================
-- Query 40: Year-wise Profit
-- Business Question:
-- How has business profit changed over the years?
-- ============================================================
select
	year(`Order Date`) as Order_Year,
    round(sum(Profit),2) as Total_Profit
from orders
group by Year(`Order Date`)
order by Order_Year;



-- ============================================================
-- Query 41: Month-wise Sales
-- Business Question:
-- Which months generate the highest sales revenue?
-- ============================================================
select
	month(`Order Date`) as Order_month,
    round(sum(Sales),2) as Total_Sales
from orders
group by month(`Order Date`)
order by Order_month;


-- ============================================================
-- Query 42: Month-wise Profit
-- Business Question:
-- Which months generate the highest profit?
-- ============================================================
select
	month(`Order Date`) as Order_month,
    round(sum(Profit),2) as Total_Sales
from orders
group by month(`Order Date`)
order by Order_month;


-- ============================================================
-- Query 43: Quarter-wise Sales
-- Business Question:
-- Which quarter generates the highest sales revenue?
-- ============================================================
select
	quarter(`Order Date`) as Order_quarter,
    round(sum(Sales),2) as Total_Sales
from orders
group by quarter(`Order Date`)
order by Order_quarter;

-- ============================================================
-- Query 44: Quarter-wise Profit
-- Business Question:
-- Which quarter generates the highest profit?
-- ============================================================
select
	quarter(`Order Date`) as Order_quarter,
    round(sum(Profit),2) as Total_Sales
from orders
group by quarter(`Order Date`)
order by Order_quarter;


-- ============================================================
-- Query 45: Day of Week Analysis
-- Business Question:
-- On which day of the week are the highest sales generated?
-- ============================================================
select 
	dayname(`Order Date`) as Day_of_Week,
    round(sum(Sales),2) as Total_Sales
    
from orders
group by dayname(`Order Date`)
order by Total_Sales;

-- ============================================================
-- Query 46: Monthly Order Trend
-- Business Question:
-- How does the number of customer orders vary by month?
-- ============================================================
select 
	monthname(`Order Date`) as Order_Month,
    count(distinct `Order ID`) as Customer_Orders
from orders
group by month(`Order Date`),monthname(`Order Date`)
order by month(`Order Date`);

-- ============================================================
		-- SECTION 5: DISCOUNT ANALYSIS
-- ============================================================

-- ============================================================
-- Query 47: Average Discount by Segment
-- Business Question:
-- Which customer segment receives the highest average discount?
-- ============================================================
use retail_sales_analysis;
select 
	`Segment`,
    round(avg(Discount),2) as Average_Discount
from orders
group by Segment
order by Average_Discount desc;
	
-- ============================================================
-- Query 48: Average Discount by State
-- Business Question:
-- Which states receive the highest average discount?
-- ============================================================

select 
	`State`,
    round(avg(Discount),2) as Average_Discount
from orders
group by State
order by Average_Discount desc;



-- ============================================================
-- Query 49: Average Discount by Ship Mode
-- Business Question:
-- Which shipping mode has the highest average discount?
-- ============================================================

select 
	`Ship Mode`,
    round(avg(Discount),2) as Average_Discount
from orders
group by `Ship Mode`
order by Average_Discount desc;



-- ============================================================
-- Query 50: Sales, Profit & Discount by Category
-- Business Question:
-- How do sales, profit, and discount vary across product categories?
-- ============================================================
select 
	Category,
    round(sum(Sales),2) as Total_Sales,
    round(sum(Profit),2) as Total_Profit,
    round(sum(Discount),2) as Total_Discount

from orders
group by Category;


-- ============================================================
-- Query 51: Products with High Discount but Negative Profit
-- Business Question:
-- Which products receive high discounts but still generate losses?
-- ============================================================
select 
	  `Product Name`,
       round(sum(Sales * Discount),2) as Total_Discount_Value,
       round(sum(Profit),2) as Net_Profit
	   
from orders
group by `Product Name`
Having sum(Profit)<0
order by Total_Discount_Value desc;


-- ============================================================
-- Query 52: Loss-making Orders
-- Business Question:
-- Which customer orders resulted in a financial loss?
-- ============================================================
select 
	`Order ID`,
    `Customer Name`,
	 round(sum(Profit),2) as Order_Profit
from orders
where Profit < 0
group by `Order ID`,`Customer Name`
order by Order_Profit asc;


-- ============================================================
-- Query 53: Discount Impact on Profit
-- Business Question:
-- How does discount affect business profitability?
-- ============================================================
SELECT 
    CASE 
        WHEN Discount = 0 THEN '0% (No Discount)'
        WHEN Discount > 0 AND Discount <= 0.2 THEN '1% - 20% Discount'
        WHEN Discount > 0.2 AND Discount <= 0.4 THEN '21% - 40% Discount'
        WHEN Discount > 0.4 AND Discount <= 0.6 THEN '41% - 60% Discount'
        ELSE 'Over 60% Discount'
    END AS Discount_Range,
    COUNT(DISTINCT `Order ID`) AS Total_Orders,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND((SUM(Profit) / SUM(Sales)) * 100, 2) AS Profit_Margin_Percent
FROM 
    orders
GROUP BY 
    1 -- Tells 




